/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as FindProfessionalsRouteImport } from './routes/find-professionals'
import { Route as JoinAsProfessionalRouteImport } from './routes/join-as-professional'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as ApiPayhereNotifyRouteImport } from './routes/api.payhere-notify'
import { Route as ProfessionalIdRouteImport } from './routes/professional.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FindProfessionalsRoute = FindProfessionalsRouteImport.update({
  id: '/find-professionals',
  path: '/find-professionals',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinAsProfessionalRoute = JoinAsProfessionalRouteImport.update({
  id: '/join-as-professional',
  path: '/join-as-professional',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPayhereNotifyRoute = ApiPayhereNotifyRouteImport.update({
  id: '/api/payhere-notify',
  path: '/api/payhere-notify',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessionalIdRoute = ProfessionalIdRouteImport.update({
  id: '/professional/$id',
  path: '/professional/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/find-professionals': typeof FindProfessionalsRoute
  '/join-as-professional': typeof JoinAsProfessionalRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/api/payhere-notify': typeof ApiPayhereNotifyRoute
  '/professional/$id': typeof ProfessionalIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/find-professionals': typeof FindProfessionalsRoute
  '/join-as-professional': typeof JoinAsProfessionalRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/api/payhere-notify': typeof ApiPayhereNotifyRoute
  '/professional/$id': typeof ProfessionalIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/find-professionals': typeof FindProfessionalsRoute
  '/join-as-professional': typeof JoinAsProfessionalRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/api/payhere-notify': typeof ApiPayhereNotifyRoute
  '/professional/$id': typeof ProfessionalIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/find-professionals'
    | '/join-as-professional'
    | '/sign-in'
    | '/sign-up'
    | '/api/payhere-notify'
    | '/professional/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/find-professionals'
    | '/join-as-professional'
    | '/sign-in'
    | '/sign-up'
    | '/api/payhere-notify'
    | '/professional/$id'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/find-professionals'
    | '/join-as-professional'
    | '/sign-in'
    | '/sign-up'
    | '/api/payhere-notify'
    | '/professional/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  FindProfessionalsRoute: typeof FindProfessionalsRoute
  JoinAsProfessionalRoute: typeof JoinAsProfessionalRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  ApiPayhereNotifyRoute: typeof ApiPayhereNotifyRoute
  ProfessionalIdRoute: typeof ProfessionalIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find-professionals': {
      id: '/find-professionals'
      path: '/find-professionals'
      fullPath: '/find-professionals'
      preLoaderRoute: typeof FindProfessionalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join-as-professional': {
      id: '/join-as-professional'
      path: '/join-as-professional'
      fullPath: '/join-as-professional'
      preLoaderRoute: typeof JoinAsProfessionalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payhere-notify': {
      id: '/api/payhere-notify'
      path: '/api/payhere-notify'
      fullPath: '/api/payhere-notify'
      preLoaderRoute: typeof ApiPayhereNotifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professional/$id': {
      id: '/professional/$id'
      path: '/professional/$id'
      fullPath: '/professional/$id'
      preLoaderRoute: typeof ProfessionalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  FindProfessionalsRoute: FindProfessionalsRoute,
  JoinAsProfessionalRoute: JoinAsProfessionalRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  ApiPayhereNotifyRoute: ApiPayhereNotifyRoute,
  ProfessionalIdRoute: ProfessionalIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
