/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FindProfessionalsRouteImport } from './routes/find-professionals'
import { Route as JoinAsProfessionalRouteImport } from './routes/join-as-professional'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FindProfessionalsRoute = FindProfessionalsRouteImport.update({
  id: '/find-professionals',
  path: '/find-professionals',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinAsProfessionalRoute = JoinAsProfessionalRouteImport.update({
  id: '/join-as-professional',
  path: '/join-as-professional',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/find-professionals': typeof FindProfessionalsRoute
  '/join-as-professional': typeof JoinAsProfessionalRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/find-professionals': typeof FindProfessionalsRoute
  '/join-as-professional': typeof JoinAsProfessionalRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/find-professionals': typeof FindProfessionalsRoute
  '/join-as-professional': typeof JoinAsProfessionalRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/find-professionals' | '/join-as-professional'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/find-professionals' | '/join-as-professional'
  id: '__root__' | '/' | '/find-professionals' | '/join-as-professional'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FindProfessionalsRoute: typeof FindProfessionalsRoute
  JoinAsProfessionalRoute: typeof JoinAsProfessionalRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find-professionals': {
      id: '/find-professionals'
      path: '/find-professionals'
      fullPath: '/find-professionals'
      preLoaderRoute: typeof FindProfessionalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join-as-professional': {
      id: '/join-as-professional'
      path: '/join-as-professional'
      fullPath: '/join-as-professional'
      preLoaderRoute: typeof JoinAsProfessionalRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FindProfessionalsRoute: FindProfessionalsRoute,
  JoinAsProfessionalRoute: JoinAsProfessionalRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
